; [env:genericSTM32F411CE]
; platform = ststm32
; board = genericSTM32F411CE
; framework = arduino

; upload_protocol = stlink
; debug_tool = stlink
; debug_speed = 100

; board_build.core = stm32

; build_flags =
;   -DUSBCON
;   -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
;   -Wl,-u,_printf_float

; lib_deps =
;   Adafruit BusIO

; monitor_speed = 115200

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

upload_protocol = stlink
debug_tool = stlink
debug_speed = 4000

build_flags =
  -DUSBCON
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
upload_flags =
  -c set CPUTAPID 0x2ba01477

lib_deps =
  Adafruit BusIO

monitor_speed = 115200