[platformio]
build_dir = ~/.pio/build/${PROJECT_HASH}

[env:genericSTM32F411CE]
platform = ststm32
board = genericSTM32F411CE
framework = arduino

upload_protocol = stlink
debug_tool = stlink
debug_speed = 8000

build_flags =
  -DUSBCON
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -Wl,-u,_printf_float
  
; upload_flags =
;   -c set CPUTAPID 0x2ba01477

monitor_speed = 115200
lib_ldf_mode = chain