[platformio]
build_dir = ~/.pio/build/${PROJECT_HASH}

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

upload_protocol = stlink
debug_tool = stlink
debug_speed = 400

build_flags =
  -DUSBCON
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  
upload_flags =
  -c set CPUTAPID 0x2ba01477
  
lib_deps =
  Adafruit BusIO

monitor_speed = 115200
lib_ldf_mode = chain+
lib_ignore =
    ArduinoOTA
    AsyncUDP
    BLE
    BluetoothSerial
    DNSServer
    ESPmDNS
    Ethernet
    FFat
    FS
    HTTPUpdateServer
    I2S
    Insights
    LittleFS
    NetBIOS
    Preferences
    RainMaker
    SD
    SD_MMC
    SimpleBLE
    SPIFFS
    Ticker
    Update
    USB
    WebServer
    WiFiProv